# Generated by Django 5.2.8 on 2025-11-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование товара', max_length=256)),
                ('description', models.CharField(help_text='Описание товара', max_length=1000)),
                ('price', models.IntegerField(default=0, help_text='Цена товара')),
            ],
        ),
    ]
