# Generated by Django 5.2.8 on 2025-11-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID цены в stripe', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='ID продукта в stripe', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Наименование товара', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0, help_text='Цена товара'),
        ),
    ]
