# Generated by Django 5.2.8 on 2025-11-17 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_item_stripe_price_id_item_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заказа')),
                ('paid', models.BooleanField(default=False, help_text='Заказ оплачен')),
                ('stripe_session_id', models.CharField(blank=True, help_text='ID сессии в stripe', max_length=255)),
                ('total_amount', models.FloatField(default=0, help_text='Сумма заказа')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Количество товаров')),
                ('item', models.ForeignKey(help_text='ID товара из таблицы Item', on_delete=django.db.models.deletion.PROTECT, to='payment.item')),
                ('order', models.ForeignKey(help_text='ID заказа из таблицы Order', on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
            ],
        ),
    ]
