# Generated by Django 5.2.8 on 2025-11-18 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Наименование скидки', max_length=255)),
                ('amount', models.FloatField(default=0, help_text='Сумма скидки')),
                ('stripe_discount_id', models.CharField(blank=True, help_text='ID скидки в stripe', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Наименование налога', max_length=255)),
                ('percent', models.FloatField(default=0, help_text='Налоговая ставка в процентах')),
                ('stripe_tax_id', models.CharField(blank=True, help_text='ID налоговой ставки в stripe', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='ID заказа из таблицы Order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Размер скидки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Налоговая ставка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.tax'),
        ),
    ]
