# Generated by Django 5.2.8 on 2025-11-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_discount_tax_alter_orderitem_order_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'RUB'), ('eur', 'EUR')], default=('rub', 'RUB'), help_text='Валюта', max_length=3),
        ),
    ]
