# Generated by Django 5.2.8 on 2025-11-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='currency',
            field=models.CharField(choices=[('rub', 'RUB'), ('eur', 'EUR')], default=('rub', 'RUB'), help_text='Валюта', max_length=3),
        ),
    ]
