# Generated by Django 5.2.8 on 2025-11-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_discount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.CharField(choices=[('rub', 'RUB'), ('eur', 'EUR')], default='rub', help_text='Валюта', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'RUB'), ('eur', 'EUR')], default='rub', help_text='Валюта', max_length=3),
        ),
    ]
