# Generated by Django 5.2.8 on 2025-11-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_discount_currency_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма скидки', max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена товара', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма заказа', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Налоговая ставка в процентах', max_digits=10),
        ),
    ]
